### ISSUE TITLE
code

### ISSUE THREAD

**Issue by CheRryLeit** [Wanghn95/code_test#1]
你好作者，我对你的研究很感兴趣，希望能够复现论文中的模型，是否可以放出完整代码呢，非常感谢！

**Comment by Wanghn95** [comment]
Hello,你好，非常感谢你对我们的论文感兴趣，现在GitHub上的代码已经是比较完整的版本了，但是由于模型本身还存在一些小的问题，所以我们想完全修正之后，再次更新网页上的代码。
很抱歉造成你的困扰^_^
